const CONFIG = Object.freeze({
  DEFAULT_PORT: 3000,
  DEFAULT_LOG_LEVEL: 'info',

  RATE_LIMIT_WINDOW_MS: 60000,
  RATE_LIMIT_MAX_REQUESTS: 100,

  INPUT_MAX_STRING_LENGTH: 1000,
  INPUT_MAX_ARRAY_LENGTH: 100,
  INPUT_MAX_NESTING_DEPTH: 5,

  RETRY_BASE_DELAY_MS: 100,
  RETRY_MAX_DELAY_MS: 5000,
  RETRY_MAX_ATTEMPTS: 3,
  RETRY_JITTER_MAX_MS: 50,

  CIRCUIT_BREAKER_THRESHOLD: 5,
  CIRCUIT_BREAKER_RESET_MS: 30000,

  HEALTH_CACHE_TTL_MS: 5000,

  MEMORY_WIPE_SAFE_THRESHOLD: 100000,
})

export default CONFIG
